# Exercícios Módulo 5. Livrarias especializadas em dados (Soluções)

Considerações a ter em conta:

* Guardar este documento com o seguinte formato para entrega: __M5_05_nome_apelido1_apelido2__
* Fazer os exercícios com as ferramentas vistas nas sessões. 
* Comentar o código
* Utilizar nomes de variáveis apropriados, se vai guardar uma nota, chamar a essa variável nota, não n ou x

**1) Trabalhar com NumPy**

* Importar numpy e usar um alias para poder utilizar os seus recursos 
* Criar um array de elementos (de 10 a 100)
* Inverter o array
* Criar um array 3x3 com valores de 0 a 8 
* Criar um array identidade de 6x6
* Criar um array com valores aleatórios com o formato 3x3x3
* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [15]:
import numpy as np
from numpy import random
elementos_10_100 = np.arange(10,101)
elementos_10_100_reverse = elementos_10_100[::-1]
print("Elementos (de 10 a 100) invertidos: ",elementos_10_100_reverse,"\n")

elementos0a8 = np.array([(2,7,1),(5,6,3),(6,4,2)])
identidade = np.identity(6)
random_geretor = random.default_rng()
arrayAleatorio = random_geretor.integers(low=1,high=10,size=(3,3,3))
print("Array 3x3 com valores de 0 a 8:\n",elementos0a8,"\n")
print("Array identidade de 6x6:\n",identidade,"\n")
print("Array com valores aleatórios com o formato 3x3x3:\n",arrayAleatorio,"\n")

arrayA = np.random.randint(0,10,(3,3))
arrayB = np.random.randint(0,10,(3,3))
print("Array A\n",arrayA,"\nArray B\n",arrayB)
if (arrayA == arrayB).all():
    print("O Array A é igual ao Array B")
else: print("Os Arrays A e B são diferentes")

Elementos (de 10 a 100) invertidos:  [100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10] 

Array 3x3 com valores de 0 a 8:
 [[2 7 1]
 [5 6 3]
 [6 4 2]] 

Array identidade de 6x6:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]] 

Array com valores aleatórios com o formato 3x3x3:
 [[[2 1 4]
  [2 4 8]
  [1 3 8]]

 [[2 4 6]
  [7 7 6]
  [2 2 2]]

 [[8 9 2]
  [5 7 2]
  [1 7 5]]] 

Array A
 [[4 8 0]
 [8 1 8]
 [2 6 3]] 
Array B
 [[4 7 8]
 [1 0 9]
 [2 3 3]]
Os Arrays A e B são diferentes


**2) Seguir com NumPy**

* Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (podem ser números inteiros). 
* Este array irá chamar-se dólares
* Fazer a conversão dos preços em dólares do primeiro array para um segundo array que se vai chamar euros. Devemos utilizar a  seguinte conversão: 
  - 1 USD = 0,874413 EUR
* Mostrar o resultado do array de euros, arredondando a 2 casas decimais.

In [18]:
import numpy as np
from numpy import random
gerador_aleatorio = random.default_rng()
dolares = gerador_aleatorio.integers(low=1,high=1000,size=100)

list_euros = []

print('Dólares a converter em euros:\n', dolares)

for euro in dolares:
    euro = "{:.2f}".format(euro*0.874413)
    list_euros.append(float(euro))
    
print('\nDólares convertidos em Euros:\n', list_euros)

Dólares a converter em euros:
 [803 580 869 521 492 718  62 876 866 368 811 478 191 407 825  32 666 583
 522  58 658  55 609 496  31 509 359 549 352 702 773 289 945 685 345 344
 394 717 949  41 848 390 532  19 280 504 757 853 827 229 342 423 561 885
 460 137 705 296   5 520 824 133 767  46 981 945 970 639 110   9 862 114
 172 252 166 703  56 763 270 154 714 303 577 831 377  35 217 793 253 619
 687 899 914 210 764  75 983 553 673 430]

Dólares convertidos em Euros:
 [702.15, 507.16, 759.86, 455.57, 430.21, 627.83, 54.21, 765.99, 757.24, 321.78, 709.15, 417.97, 167.01, 355.89, 721.39, 27.98, 582.36, 509.78, 456.44, 50.72, 575.36, 48.09, 532.52, 433.71, 27.11, 445.08, 313.91, 480.05, 307.79, 613.84, 675.92, 252.71, 826.32, 598.97, 301.67, 300.8, 344.52, 626.95, 829.82, 35.85, 741.5, 341.02, 465.19, 16.61, 244.84, 440.7, 661.93, 745.87, 723.14, 200.24, 299.05, 369.88, 490.55, 773.86, 402.23, 119.79, 616.46, 258.83, 4.37, 454.69, 720.52, 116.3, 670.67, 40.22, 857.8, 826.32, 848.18, 558.75, 

**3) Trabalhar com pandas**

* Importar pandas e usar um alias para poder utilizar os seus recursos.
* Carregar como dataframe de pandas csv 05_05_imdb_títulos.csv e mostrar os seus 5 primeiros registos.
* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos
* Mostrar o número de registos do dataframe de títulos.
* Mostrar o número de registos do dataframe de elenco.
* Mostrar os 5 titulos mais antigas.
* Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?
* Mostrar os 10 títulos mais comuns (que mais se repetem).
* Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.
* Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.
* Mostrar quantos filmes foram feitas no ano 1950.
* Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).
* Mostrar todas os papéis que teve a trilogia “The Godfather”, agrupando pelo papel e forneca a informação da quantidade de vezes esse papel apareceu (exemplo: michael corleone aparece nos 3 filmes da triologia).
* Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958.
* Mostrar quantos papéis teve “Bruce Wayne” como protagonista (Dica: Em Batman de 1989, existe Bruce Wayne e tambem Young Bruce Wayne, que deverão ambos aparecer).
* Mostrar quantos papéis fez “Robert de Niro” na sua carreira.
* Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado  por ano de forma descendente.
* Mostrar quantos papéis para atores teve na década 50’s.
* Mostrar quantos papéis para atrizes teve na década 50’s.

In [15]:
# IMPORTAR PANDAS USANDO UM ALIAS
import pandas as pd

# IMPORTAR UM CONTADOR PARA UM PASSO MAIS Â FRENTE
from collections import Counter

# CARREGAR COMO DATA FRAME DE PANDAS OS TÍTULOS
csv_titulos_imdb = pd.read_csv('05_05_imdb_titulos.csv')

# MOSTRAR OS SEUS 5 PRIMEIRO REGISTOS
csv_titulos_imdb.head(6)


title  year
0                                 Mahler  1974
1           Ogon, voda i... mednye truby  1968
2  Ana Nojoom bent alasherah wamotalagah  2014
3                      Malu de Bicicleta  2010
4             Nazareno Apostol: Boy Ahas  1989
5                     Ya ba yu xin niang  1971

In [3]:
# CARREGAR COMO DATA FRAME DE PANDAS O ELENCO
elenco_imdb = pd.read_csv('05_05_imdb_elenco.csv')

# MOSTRAR OS SEUS 5 PRIMEIRO REGISTOS
elenco_imdb.head(6)

title  year      name   type                character  \
0          Closet Monster  2015  Buffy #1  actor                  Buffy 4   
1         Suuri illusioni  1985    Homo $  actor                   Guests   
2     Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan   
3    Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   
4              Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   
5  Straight Outta Compton  2015   $hutter  actor              Club Patron   

      n  
0  31.0  
1  22.0  
2  10.0  
3   NaN  
4   NaN  
5   NaN

In [4]:
# MOSTRAR O NÚMERO DE REGISTOS
print(f'Número de Registos de Títulos - {len(csv_titulos_imdb)}')
print(f'\nNúmero de Registos de Elenco - {len(elenco_imdb)}')

Número de Registos de Títulos - 230407

Número de Registos de Elenco - 3564650


In [5]:
# MOSTRAR 0S 5 TÍTULOS MAIS ANTIGOS
filmesAntigos = csv_titulos_imdb.sort_values(by=['year'])[:5]
print(f"\n5 Filmes mais antigos: \n{filmesAntigos}")


5 Filmes mais antigos: 
                                                    title  year
13229                                          Miss Jerry  1894
103233                                 The Startled Lover  1898
133020     Reproduction of the Corbett and Jeffries Fight  1899
51528                                Family Troubles (II)  1900
195127  Pierrot's Problem, or How to Make a Fat Wife O...  1900


In [59]:
# MOSTRAR OS FILMES QUE CONTÉM DRÁCULA NO TÍTULO E MOSTRAR QUANTOS SÃO
dracula = csv_titulos_imdb[csv_titulos_imdb['title'].str.contains('Dracula', case = False)]
print(dracula)
dracula.count()

                                  title  year
3903         Bonnie & Clyde vs. Dracula  2008
4851                   House of Dracula  1945
13441                    Batman Dracula  1964
15371   Young-guwa heubhyeolgwi dracula  1992
20794                 Terror of Dracula  2012
...                                 ...   ...
214826                    Dracula's Dog  1978
221137                      Dracula Now  2015
224233     The Satanic Rites of Dracula  1973
228121                   Son of Dracula  1974
229161               Dracula and Stoker  2012

[84 rows x 2 columns]


title    84
year     84
dtype: int64

In [80]:
# MOSTRAR OS 10 TÍTULOS MAIS COMUNS
titulosComuns = csv_titulos_imdb.title.value_counts().head(10)
print(titulosComuns)

Hamlet                  19
Carmen                  16
Macbeth                 15
Maya                    11
The Outsider            11
Hero                    11
Othello                 11
The Three Musketeers    11
Anna                    10
Vengeance               10
Name: title, dtype: int64


In [61]:
# MOSTRAR QUAL FOI O PRIMEIRO FILME CHAMADO ROMEO AND JULIET
romeoJuliet = csv_titulos_imdb[csv_titulos_imdb['title'] == 'Romeo and Juliet'].sort_values('year').head(1)
print(romeoJuliet)

                   title  year
124702  Romeo and Juliet  1916


In [62]:
# LISTAR TODOS OS FILMES QUE CONTEM A PALAVRA EXORCIST, EM ORDEM CRESCENTE
exorcist = csv_titulos_imdb[csv_titulos_imdb['title'].str.contains('Exorcist', case = False)].sort_values('year')
print(exorcist)

                                         title  year
88003                             The Exorcist  1973
49658                  O Exorcista de Mulheres  1974
118920     Satanico Pandemonium: La Sexorcista  1975
140519                Exorcist II: The Heretic  1977
220073                        Kung Fu Exorcist  1978
17375                         The Exorcist III  1990
132451                        Teenage Exorcist  1991
117797                 Exorcist: The Beginning  2004
94189        Dominion: Prequel to the Exorcist  2005
209250  Costa Chica: Confession of an Exorcist  2006
86354                      Exorcist Chronicles  2007
130686                      The Disco Exorcist  2011
57932                      Exorcist Chronicles  2013
69974                           Shark Exorcist  2015
51101                            Bad Exorcists  2015
151850                              Exorcistas  2015
60700                      Accidental Exorcist  2016
161093                       American Exorcist

In [63]:
# MOSTRAR QUANTOS FILMES FORAM FEITOS EM 1950
filmes1950 = csv_titulos_imdb[csv_titulos_imdb['year'] == 1950].sort_values('year').count()
print(filmes1950)

title    1081
year     1081
dtype: int64


In [64]:
# MOSTRAR QUANTOS FILMES FORAM FEITOS ENTRE 1950 E 1959
filmes1950_1959 = csv_titulos_imdb[csv_titulos_imdb['year'].isin([1950, 1960])].sort_values('year').count()
print(filmes1950_1959)


title    2569
year     2569
dtype: int64


In [66]:
# MOSTRAR TODOS OS PAPEIS DA TRILOGIA THE GODFATHER
godfather = elenco_imdb[elenco_imdb['title'] == 'The Godfather']
print(godfather)

                 title  year                  name     type  \
51214    The Godfather  1972       Chris Anastasio    actor   
102809   The Godfather  1972      Norm Bacchiocchi    actor   
220852   The Godfather  1972             Rudy Bond    actor   
248000   The Godfather  1972         Marlon Brando    actor   
248738   The Godfather  1972            Max Brandt    actor   
...                ...   ...                   ...      ...   
3137607  The Godfather  1972          Carol Morley  actress   
3360381  The Godfather  1972       Ardell Sheridan  actress   
3363276  The Godfather  1972           Talia Shire  actress   
3390198  The Godfather  1972    Filomena Spagnuolo  actress   
3399922  The Godfather  1972  Simonetta Stefanelli  actress   

                               character     n  
51214                          Policeman   NaN  
102809             Luca Brasi's Assassin   NaN  
220852                             Cuneo  15.0  
248000                 Don Vito Corleone   1.0 

In [68]:
# MOSTRAR O ELENCO DO FILME DRACULA DE 1958, ORDENADO PELA CLASSIFICAÇÃO N
draculaElenco = elenco_imdb
draculaElenco = draculaElenco[(draculaElenco.title == "Dracula") & (draculaElenco.year == 1958)] 
draculaElenco = draculaElenco.sort_values("n")
print(draculaElenco)

           title  year                   name     type  \
485197   Dracula  1958          Peter Cushing    actor   
1242307  Dracula  1958        Christopher Lee    actor   
1242308  Dracula  1958        Christopher Lee    actor   
822398   Dracula  1958          Michael Gough    actor   
3410427  Dracula  1958      Melissa Stribling  actress   
3069196  Dracula  1958            Carol Marsh  actress   
2677557  Dracula  1958            Olga Dickie  actress   
2220986  Dracula  1958        John Van Eyssen    actor   
2777216  Dracula  1958          Valerie Gaunt  actress   
2731182  Dracula  1958            Janina Faye  actress   
2444220  Dracula  1958         Barbara Archer  actress   
1285506  Dracula  1958     Charles Lloyd Pack    actor   
1453367  Dracula  1958         George Merritt    actor   
2357769  Dracula  1958      George Woodbridge    actor   
171732   Dracula  1958          George Benson    actor   
1347640  Dracula  1958         Miles Malleson    actor   
148496   Dracu

In [75]:
# MOSTRAR QUANTOS PAPEIS BRUCE WAYNE TEVE COMO PROTAGONISTA
bruceWayne1 = elenco_imdb
bruceWayne1 = bruceWayne1[bruceWayne1.character == "Bruce Wayne"]
bruceWayne1 = bruceWayne1[bruceWayne1.n == 1]
bruceWayne1.count()

title        20
year         20
name         20
type         20
character    20
n            20
dtype: int64

In [71]:
# MOSTRAR QUANTOS PAPEIS ROBERT DE NIRO FEZ NA SUA CARREIRA
robertDeNiro = elenco_imdb[elenco_imdb["name"] == "Robert De Niro"].count()
print(robertDeNiro)

title        103
year         103
name         103
type         103
character    103
n             95
dtype: int64


In [76]:
# LISTAR OS PAPEIS DE PROTAGONISTA DE CHARLTON HESTON NOS ANOS 60, DE FORMA DESCENDENTE
charltonHeston = elenco_imdb
charltonHeston = charltonHeston[charltonHeston.name == "Charlton Heston"]
charltonHeston = charltonHeston[charltonHeston.n == 1]
charltonHeston = charltonHeston[(charltonHeston.year >=1960) & (charltonHeston.year <= 1969)]
charltonHeston = charltonHeston.sort_values('year',ascending=False)
print(charltonHeston)

                            title  year             name   type  \
944074                 Number One  1969  Charlton Heston  actor   
944077         Planet of the Apes  1968  Charlton Heston  actor   
944050               Counterpoint  1967  Charlton Heston  actor   
944120                 Will Penny  1967  Charlton Heston  actor   
944066                   Khartoum  1966  Charlton Heston  actor   
944068               Major Dundee  1965  Charlton Heston  actor   
944085  The Agony and the Ecstasy  1965  Charlton Heston  actor   
944111               The War Lord  1965  Charlton Heston  actor   
944038          55 Days at Peking  1963  Charlton Heston  actor   
944052               Diamond Head  1962  Charlton Heston  actor   
944101  The Pigeon That Took Rome  1962  Charlton Heston  actor   
944102  The Pigeon That Took Rome  1962  Charlton Heston  actor   
944103  The Pigeon That Took Rome  1962  Charlton Heston  actor   
944054                     El Cid  1961  Charlton Heston  acto

In [78]:
# MOSTRAR QUANTOS PAPEIS PARA ATORES HOUVE NA DÉCADA DE 50
papeisAtores50 = elenco_imdb[(elenco_imdb["type"] == "actor") & elenco_imdb["year"].isin([1950, 1960])].count()
print(papeisAtores50)

title        29365
year         29365
name         29365
type         29365
character    29365
n            15488
dtype: int64


In [79]:
# MOSTRAR QUANTOS PAPEIS PARA ATRIZES HOUVE NA DÉCADA DE 50
papeisAtrizes50 = elenco_imdb[(elenco_imdb["type"] == "actress") & elenco_imdb["year"].isin([1950, 1960])].count()
print(papeisAtrizes50)

title        10788
year         10788
name         10788
type         10788
character    10788
n             6849
dtype: int64
